# Generated by Django 3.2.9 on 2024-03-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_application_payment_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='order_type',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('takeaway', 'Take away')], default='onsite', max_length=255),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('users', models.ManyToManyField(to='users.User')),
            ],
        ),
    ]
