# Generated by Django 3.2.9 on 2024-03-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20240306_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='order_type',
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
