# Generated by Django 3.2.9 on 2024-03-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20240306_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='order_type',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('takeaway', 'Take away')], default='onsite', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='phone2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique_for_date=True)),
                ('users', models.ManyToManyField(to='users.User')),
            ],
        ),
    ]
