# Generated by Django 3.2.9 on 2024-03-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20240306_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_check_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
