# Generated by Django 3.2.9 on 2024-03-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='_sent_to_admin',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
